### ISSUE TITLE
Unused parameters in `rklib_variable_steps.f90`

### ISSUE THREAD

**Issue by HugoMVale** [jacobwilliams/rklib#14]
I've just built the lib with `fpm build --verbose` and noticed some warnings about unused parameters in `rklib_variable_steps.f90`. Maybe it's nothing, but it could also be the consequence of some typo (e.g., one parameter is used two twice and another none).

**Comment by jacobwilliams** [comment]
it was ok. some were because of FSAL, and another because a difference was 0 so the variable wasn't needed.
