### ISSUE TITLE
Is check `if (h==zero)` required?

### ISSUE THREAD

**Issue by HugoMVale** [jacobwilliams/rklib#15]
All fixed-step methods have the following check at the start:
```fortran
if (h==zero) then
    xf = x
    return
end if
```
I have the impression that this check is not required and actually a bit "detrimental":
* strictly speaking, a real==real comparison is questionable.
* if such a check were necessary, wouldn't it be preferable to move it up the procedure hierarchy, to avoid repeating it in every step call and every method implementation (DRY principle)?
* all methods must anyway be consistent, in the sense that dx = xf -x must be 0 for h=0. So, there is no need to protect against a step call with h=0.

**Comment by jacobwilliams** [comment]
yes I agree and was thinking about removing it... I need to check the calling routine just to make sure it can never happen.
