### ISSUE TITLE
Structure of the files

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/rklib#18]
I moved stuff into Fortran submodules because I didn't want everything all in one file. But then I didn't like all that boilerplate that had to be in the main file, so I moved those into `.inc` files, which isn't great either. 

Is there a better way? 

Also, GitHub thinks the `.inc` files are C++. Is there an extension it would recognize as a Fortran include file?

**Comment by HugoMVale** [comment]
I have literally 0 experience with *.inc files. I know it's a pre-processor thing and that's it...
Regarding the file association, there might be a [way](https://webapps.stackexchange.com/questions/31654/force-github-syntax-highlighting-language-on-source-files).

**Comment by jacobwilliams** [comment]
Note: all the boilerplate files can now be autogenerated by updated the tables in `generate_files.py` and running that script:

`python generate_files.py`
