### ISSUE TITLE
Discrepancy between some rational number coefficients and their decimal values

### ISSUE THREAD

**Issue by xecej4** [jacobwilliams/rklib#36]
Lines 3950-3954 of file rklib_variable_steps.f90 read:

```fortran
real(wp),parameter :: d7   = 7170564158.0_wp / 30263027435.0_wp    ! 0.01158056612815422_wp
real(wp),parameter :: d8   = 7206303747.0_wp / 16758195910.0_wp    ! -0.7627079959184843_wp
real(wp),parameter :: d9   = -1059739258.0_wp / 8472387467.0_wp    ! 2.046330367018225_wp
real(wp),parameter :: d10  = 16534129531.0_wp / 11550853505.0_wp   ! -4.163198889384351_wp
real(wp),parameter :: d11  = -3.0_wp / 2.0_wp                      ! 2.901200440989918_wp
```

The decimal value shown in the comment section of each of these lines does not agree with the rational number on the same line, sometimes even the sign is wrong. Look, for example, at d11.

**Comment by jacobwilliams** [comment]
1. Rational coefficients are from here: http://users.uoa.gr/~tsitourasc/rktp86.m
2. The floating point ones were from here: https://www.mathworks.com/matlabcentral/fileexchange/2911-ode86

The reference seems to match the first one.. at least for this `d11` coefficient. maybe the 2nd one is wrong or this is just a different set of coefficients? I'll look into it.

**Comment by jacobwilliams** [comment]
ah I see, these terms in the comments are really the `e` coefficients. I'll just remove the comments, I don't think they are necessary.
